sudo: required
services:
- docker
before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu
  $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y install docker-ce
script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- cd ruby-bionic; docker build -t $DOCKER_USERNAME/ruby-bionic .
- cd ../video-transcoding; docker build -t $DOCKER_USERNAME/video-transcoding .
- docker images
deploy:
  provider: script
  script:
  - docker push $DOCKER_USERNAME/ruby-bionic
  - docker push $DOCKER_USERNAME/video-transcoding
  on:
    branch: master
env:
  global:
    - DOCKER_USERNAME="computerfr33k"
    - secure: c0XRiNGDin1MLofMqxzlRyEgqon9mZU0TLMrsYqDbekyLnA2FNM6CPETrnV1qtIFu9go/3SuNQLkFrFicfuIsAeET24oYDMgC2C+r74hZmk8lOPKLN9YJLCb+1HnzEjfmLRQXeN3VtB0y8lyA6eEhCJ0QTbQv3jX4/uf+VAo4abWELjwBJ/dlJjY9CjUniF3SFiykp1I+T8Q3VwabA/7lFvQOPvdK01hfSLG1iR7E2v4WaYTiBELqJ/I1Pcj0jKMp4a4NdL1GwGy61PwwjSaowuonS5HGn0vFCsYw8gPJll23TYaT9eEvw474T64yOZgBKIETMM+S+G/POCVUuyqpQaffdAPyUJqiUC3SCicYanqJ0tRtJU3mwUjm0b+6YnW400TPpSpaHQ2yPIJVxN87150Yun7n39c7RIeQjcrzDypDqzH7sjhmbUcoMICb/FDrlfJhj9ujie2tZ3qf2srBrEjl33ifuqBCdzqfbxrt5BefHJHi2YfWp0jcsbRhB54Tz4XgtNRQNwSbiAgXJWqp9AzUbuMbnodMJXmq48Fc/EI3XwEJukje7VGnxjV5mK7ssYSbYDqCLquGV93O0HuDpqspC8bJ9W7ZZDjZSVUpmu88CA0fQjS79CDcFN2zH39pJ7KBV+X/xhHgcZbvlBHuCp5zrU7sf5phyN3rJI6B+k=
